SELECT USER_ID, PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(ONLINE_SALE_ID) CNT
FROM ONLINE_SALE OS
GROUP BY OS.USER_ID, OS.PRODUCT_ID) T
WHERE T.CNT > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC


#SELECT OS.USER_ID, OS.PRODUCT_ID, COUNT(*) CNT
#FROM ONLINE_SALE OS
#GROUP BY OS.USER_ID, OS.PRODUCT_ID
