SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, T.AVG_REVIEW AS SCORE
FROM REST_INFO RI
JOIN (SELECT RR.REST_ID, ROUND(AVG(RR.REVIEW_SCORE),2) AVG_REVIEW
FROM REST_REVIEW RR
GROUP BY RR.REST_ID) T ON RI.REST_ID = T.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
ORDER BY T.AVG_REVIEW DESC, RI.FAVORITES DESC;

#SELECT GROUP_CONCAT("'",RI.REST_ID,"'")
#FROM REST_INFO RI
#WHERE RI.ADDRESS LIKE '%서울%'

#SELECT RR.REST_ID, ROUND(AVG(RR.REVIEW_SCORE),2)
#FROM REST_REVIEW RR
#WHERE RR.REST_ID IN('00001','00002','00003','00004','00005','00008')
##GROUP BY RR.REST_ID