SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
(T.MAX_SIZE- ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
FROM ECOLI_DATA ED
LEFT JOIN (SELECT DATE_FORMAT(ED.DIFFERENTIATION_DATE, '%Y') AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA ED
GROUP BY DATE_FORMAT(ED.DIFFERENTIATION_DATE, '%Y')) T ON T.YEAR = DATE_FORMAT(ED.DIFFERENTIATION_DATE, '%Y')
ORDER BY YEAR, YEAR_DEV;