SELECT FI.ID, T.FISH_NAME, T.LENGTH
FROM (
    SELECT MAX(FI.LENGTH) AS LENGTH, FNI.FISH_NAME, FI.FISH_TYPE
    FROM FISH_INFO FI
    LEFT JOIN FISH_NAME_INFO FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
    GROUP BY FI.FISH_TYPE, FNI.FISH_NAME ) T
LEFT JOIN FISH_INFO FI ON (FI.FISH_TYPE = T.FISH_TYPE AND FI.LENGTH = T.LENGTH)
ORDER BY FI.ID